#!/usr/bin/env python3
"""Render every Asterisk config file from deploy/trunks.csv, deploy/extensions.csv and .env
into asterisk/etc/ (git ignored, contains secrets). Stdlib only. Run on the VPS before
`docker compose up`; scripts/vps-deploy.sh does it for you.

    python3 scripts/render_conf.py [--root DIR] [--out DIR]

Extension passwords are generated once and kept in deploy/extension_secrets.txt, so a re-render
never changes a working softphone.
"""
import argparse, csv, ipaddress, os, secrets, sys
from pathlib import Path

BD_PATTERNS = ["_01XXXXXXXXX", "_02XXXXXXXX", "_0[3-9]XXXXXXXX", "_880XXXXXXXXXX"]   # no 00, no +, so no ISD


def read_env(path: Path) -> dict:
    env = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip().strip('"').strip("'")
    return env


def read_csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as f:
        return [dict((k.strip(), (v or "").strip()) for k, v in row.items()) for row in csv.DictReader(f)]


def load_secrets(path: Path, extensions: list[str]) -> dict:
    found = {}
    if path.exists():
        for line in path.read_text().splitlines():
            parts = line.split()
            if len(parts) == 2:
                found[parts[0]] = parts[1]
    changed = False
    for e in extensions:
        if e not in found:
            found[e] = secrets.token_urlsafe(18); changed = True
    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("".join(f"{k} {v}\n" for k, v in found.items()))
        os.chmod(path, 0o600)
    return found


def bizs_of(trunks):
    out = {}
    for t in trunks:
        out.setdefault(t["biz"], []).append(t)
    return dict(sorted(out.items()))


def ring_group_of(biz: str) -> str:
    return str(600 + int(biz.replace("biz", "")))


def render_pjsip(env, trunks, exts, ext_secrets) -> str:
    public_ip = env.get("PUBLIC_IP", "")
    domain = env.get("PBX_DOMAIN", "")
    ext_allow = [c for c in env.get("EXTENSION_ALLOW_CIDR", "").split(",") if c.strip()]
    o = []
    o.append(";; generated by scripts/render_conf.py, do not edit\n")
    o.append("[global]\ntype=global\nuser_agent=bd-voice-stack\nendpoint_identifier_order=ip,username,auth_username\n")
    o.append("[transport-udp]\ntype=transport\nprotocol=udp\nbind=0.0.0.0:5060\n"
             f"external_media_address={public_ip}\nexternal_signaling_address={public_ip}\n"
             "local_net=172.16.0.0/12\nlocal_net=10.0.0.0/8\nlocal_net=192.168.0.0/16\nallow_reload=yes\n")
    for t in trunks:
        n, host, port = t["name"], t["host"], t.get("port") or "5060"
        codecs = [c.strip() for c in t.get("codecs", "ulaw,alaw").replace("&", ",").split(",") if c.strip()]
        allow = "".join(f"allow={c}\n" for c in codecs)
        o.append(f"\n;; ---- trunk {n} ({t['biz']} {t['number']}) ----\n")
        if t.get("register", "yes").lower() == "yes":
            o.append(f"[{n}]\ntype=registration\noutbound_auth={n}-auth\nserver_uri=sip:{host}:{port}\n"
                     f"client_uri=sip:{t['username']}@{host}\nretry_interval=60\nforbidden_retry_interval=600\n"
                     f"expiration=3600\nline=yes\nendpoint={n}\n")
        o.append(f"[{n}-auth]\ntype=auth\nauth_type=userpass\nusername={t['username']}\npassword={t['secret']}\n")
        o.append(f"[{n}]\ntype=aor\ncontact=sip:{host}:{port}\nqualify_frequency=60\n")
        o.append(f"[{n}]\ntype=endpoint\ncontext=from-trunk\ndisallow=all\n{allow}outbound_auth={n}-auth\naors={n}\n"
                 f"from_user={t['username']}\nfrom_domain={host}\ndirect_media=no\nrtp_symmetric=yes\nforce_rport=yes\n"
                 f"rewrite_contact=yes\nsend_pai=yes\nset_var=BIZ={t['biz']}\nset_var=DID={t['number']}\n")
        o.append(f"[{n}]\ntype=identify\nendpoint={n}\nmatch={host}\n")
    for e in exts:
        x = e["extension"]
        o.append(f"\n;; ---- extension {x} {e['name']} ({e['biz']}) ----\n")
        o.append(f"[{x}]\ntype=endpoint\ncontext=from-internal\ndisallow=all\nallow=ulaw\nallow=alaw\nauth={x}\naors={x}\n"
                 f"callerid=\"{e['name']}\" <{x}>\ndirect_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n"
                 f"set_var=BIZ={e['biz']}\n")
        o.append(f"[{x}]\ntype=auth\nauth_type=userpass\nusername={x}\npassword={ext_secrets[x]}\n")
        o.append(f"[{x}]\ntype=aor\nmax_contacts=3\nremove_existing=yes\nqualify_frequency=30\n")
        if ext_allow:
            o.append(f"[{x}]\ntype=acl\n" + "".join(f"permit={c.strip()}\n" for c in ext_allow) + "deny=0.0.0.0/0\n")
    if domain:
        o.append(f"\n;; softphones register to sip:{domain} (A record -> {public_ip})\n")
    return "".join(o)


def render_extensions(env, trunks, exts, bridge_host) -> str:
    bizs = bizs_of(trunks)
    ext_by_biz = {}
    for e in exts:
        ext_by_biz.setdefault(e["biz"], []).append(e["extension"])
    o = []
    o.append(";; generated by scripts/render_conf.py, do not edit\n[general]\nstatic=yes\nwriteprotect=no\nclearglobalvars=no\n\n[globals]\n")
    for biz, ts in bizs.items():
        o.append(f"{biz.upper()}_NUMBER={ts[0]['number']}\n")
    # inbound from the operator: the trunk endpoint carries BIZ and DID (set_var)
    o.append("\n[from-trunk]\nexten => _X.,1,NoOp(inbound DID=${DID} biz=${BIZ} from ${CALLERID(num)})\n"
             " same => n,Goto(ai-agent,${BIZ},1)\nexten => s,1,Goto(_X.,1)\n"
             "exten => h,1,NoOp(hangup ${BIZ} ${CALLERID(num)})\n")
    # AI agent (verified against Asterisk 21 source: AudioSocket needs a real UUID, sets no status
    # variable, returns 0 on the 0x00 hangup frame, -1 on failure; TryExec turns -1 into TRYSTATUS)
    o.append(f"""
[ai-agent]
exten => _biz.,1,NoOp(AI agent for ${{EXTEN}} DID=${{DID}} CID=${{CALLERID(num)}})
 same => n,Answer()
 same => n,Set(BIZ=${{EXTEN}})
 same => n,Set(AI_UUID=${{UUID()}})
 same => n,Set(TRANSFER_TARGET=)
 same => n,Set(DB(aibridge/${{AI_UUID}})=${{CHANNEL}})
 same => n,Set(CHANNEL(hangup_handler_push)=ai-agent-cleanup,s,1)
 same => n,Set(CALLFILENAME=${{STRFTIME(${{EPOCH}},,%Y%m%d-%H%M%S)}}-${{EXTEN}}-${{CALLERID(num)}}-${{UNIQUEID}})
 same => n,MixMonitor(${{CALLFILENAME}}.wav,b)
 same => n,Wait(0.2)
 same => n,TryExec(AudioSocket(${{AI_UUID}},{bridge_host}))
 same => n,NoOp(AudioSocket ended TRYSTATUS=${{TRYSTATUS}} TRANSFER_TARGET=${{TRANSFER_TARGET}})
 same => n,Set(DB_DELETE(aibridge/${{AI_UUID}})=)
 same => n,GotoIf($["${{TRANSFER_TARGET}}" != ""]?xfer)
 same => n,GotoIf($["${{TRYSTATUS}}" != "SUCCESS"]?fallback)
 same => n,Hangup()
 same => n(xfer),NoOp(transfer to human ${{TRANSFER_TARGET}})
 same => n,Goto(from-internal,${{TRANSFER_TARGET}},1)
 same => n(fallback),NoOp(bridge down or failed, ringing the humans)
 same => n,Goto(ai-fallback,${{EXTEN}},1)

[ai-agent-cleanup]
exten => s,1,Set(DB_DELETE(aibridge/${{AI_UUID}})=)
 same => n,Return()

[ai-fallback]
""")
    for biz in bizs:
        o.append(f"exten => {biz},1,Goto(from-internal,{ring_group_of(biz)},1)\n")
    # internal: extensions, ring groups, outbound (Bangladesh only, pinned to the caller's business)
    o.append("\n[from-internal]\n")
    for e in exts:
        o.append(f"exten => {e['extension']},1,Dial(PJSIP/{e['extension']},25)\n same => n,Hangup()\n")
    for biz in bizs:
        members = "&".join(f"PJSIP/{x}" for x in ext_by_biz.get(biz, []))
        grp = ring_group_of(biz)
        if members:
            o.append(f"exten => {grp},1,NoOp(ring group {biz})\n same => n,Dial({members},25)\n"
                     f" same => n,Playback(vm-nobodyavail)\n same => n,Hangup()\n")
        else:
            o.append(f"exten => {grp},1,Playback(vm-nobodyavail)\n same => n,Hangup()\n")
    for p in BD_PATTERNS:
        o.append(f"exten => {p},1,Gosub(outbound,s,1(${{EXTEN}}))\n same => n,Hangup()\n")
    o.append("\n[outbound]\nexten => s,1,NoOp(outbound from ${CALLERID(num)} biz=${BIZ} to ${ARG1})\n")
    for biz in bizs:
        o.append(f' same => n,GotoIf($["${{BIZ}}" = "{biz}"]?{biz})\n')
    o.append(" same => n,NoOp(extension has no business, refusing outbound)\n same => n,Hangup(21)\n")
    for biz, ts in bizs.items():
        o.append(f" same => n({biz}),Set(CALLERID(num)={ts[0]['number']})\n")
        for i, t in enumerate(ts):
            nxt = f"{biz}_t{i+1}" if i + 1 < len(ts) else None
            o.append(f" same => n,Dial(PJSIP/${{ARG1}}@{t['name']},60)\n")
            if nxt:
                o.append(f' same => n,GotoIf($["${{DIALSTATUS}}" = "CHANUNAVAIL" | "${{DIALSTATUS}}" = "CONGESTION"]?{nxt})\n')
                o.append(" same => n,Return()\n")
                o.append(f" same => n({nxt}),NoOp(failover to {t['name']})\n")
        o.append(" same => n,Return()\n")
    return "".join(o)


def render_manager(env) -> str:
    return (";; generated by scripts/render_conf.py\n[general]\nenabled=yes\nwebenabled=no\nbindaddr=0.0.0.0\nport=5038\n\n"
            f"[{env.get('AMI_USER', 'aibridge')}]\nsecret={env['AMI_SECRET']}\ndeny=0.0.0.0/0.0.0.0\n"
            "permit=172.16.0.0/255.240.0.0\npermit=10.0.0.0/255.0.0.0\npermit=192.168.0.0/255.255.0.0\n"
            "read=call,command\nwrite=call,command\n")


STATIC = {
    "asterisk.conf": "[directories]\nastetcdir => /etc/asterisk\nastmoddir => /usr/lib/asterisk/modules\nastvarlibdir => /var/lib/asterisk\n"
                     "astdbdir => /var/lib/asterisk/db\nastkeydir => /var/lib/asterisk\nastdatadir => /var/lib/asterisk\n"
                     "astagidir => /var/lib/asterisk/agi-bin\nastspooldir => /var/spool/asterisk\nastrundir => /var/run/asterisk\n"
                     "astlogdir => /var/log/asterisk\nastsbindir => /usr/sbin\n\n[options]\nrunuser = asterisk\nrungroup = asterisk\n"
                     "verbose = 3\ndefaultlanguage = en\n",
    "modules.conf": "[modules]\nautoload=yes\nnoload => chan_sip.so\nnoload => res_hep.so\nnoload => res_hep_pjsip.so\nnoload => res_hep_rtcp.so\n",
    "logger.conf": "[general]\ndateformat=%F %T\n\n[logfiles]\nconsole => notice,warning,error\nmessages => notice,warning,error\n"
                   "security => security\nfull => notice,warning,error,verbose,dtmf\n",
    "musiconhold.conf": "[default]\nmode=files\ndirectory=moh\n",
    "features.conf": "[general]\ntransferdigittimeout = 3\n",
    "cdr.conf": "[general]\nenable=yes\n",
    "acl.conf": "",
    "pjsip_notify.conf": "",
    "res_pjsip_outbound_registration.conf": "",
    "extconfig.conf": "[settings]\n",
    "indications.conf": "[general]\ncountry=bd\n\n[bd]\ndescription = Bangladesh\nringcadence = 1000,4000\ndial = 425\nbusy = 425/500,0/500\n"
                        "ring = 425/1000,0/4000\ncongestion = 425/250,0/250\n",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    ap.add_argument("--out", default=None)
    ap.add_argument("--bridge", default="ai-bridge:9092")
    a = ap.parse_args()
    root = Path(a.root)
    out = Path(a.out) if a.out else root / "asterisk" / "etc"
    env = read_env(root / ".env")
    for k in ("AMI_SECRET", "PUBLIC_IP"):
        if not env.get(k) or env[k] == "CHANGE_ME":
            sys.exit(f"{k} missing or CHANGE_ME in .env")
    ipaddress.ip_address(env["PUBLIC_IP"])
    trunks = read_csv(root / "deploy" / "trunks.csv")
    exts = read_csv(root / "deploy" / "extensions.csv")
    if any("CHANGE_ME" in t.get("secret", "") for t in trunks):
        sys.exit("deploy/trunks.csv still has CHANGE_ME secrets")
    ext_secrets = load_secrets(root / "deploy" / "extension_secrets.txt", [e["extension"] for e in exts])
    out.mkdir(parents=True, exist_ok=True)
    files = dict(STATIC)
    files["rtp.conf"] = f"[general]\nrtpstart={env.get('RTP_START', '10000')}\nrtpend={env.get('RTP_FINISH', '10200')}\nstrictrtp=yes\n"
    files["pjsip.conf"] = render_pjsip(env, trunks, exts, ext_secrets)
    files["extensions.conf"] = render_extensions(env, trunks, exts, a.bridge)
    files["manager.conf"] = render_manager(env)
    for name, body in files.items():
        (out / name).write_text(body, encoding="utf-8")
    os.chmod(out, 0o750)
    for name in ("pjsip.conf", "manager.conf"):
        os.chmod(out / name, 0o640)
    print(f"rendered {len(files)} files to {out}: {len(trunks)} trunks, {len(exts)} extensions, "
          f"ring groups {', '.join(ring_group_of(b) for b in bizs_of(trunks))}")
    print(f"extension passwords: {root / 'deploy' / 'extension_secrets.txt'}")


if __name__ == "__main__":
    main()
